services:
  frontend:
    image: source-context/frontend:dev
    build:
      context: ./frontend
      target: dev
    ports:
      - "127.0.0.1:${SOURCE_CONTEXT_FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    image: source-context/backend:dev
    build:
      dockerfile: ./backend/Dockerfile
      context: .
      target: dev
    ports:
      - "127.0.0.1:${SOURCE_CONTEXT_BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
#      - workspace_repos:/app/workspace-repositories

  celery-worker:
    image: source-context/backend:dev
    build:
      dockerfile: ./backend/Dockerfile
      context: .
      target: dev
    command: uv run celery -A app.worker.celery_worker worker --loglevel=info
    volumes:
      - ./backend:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
#      - workspace_repos:/app/workspace-repositories

  postgres:
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  neo4j:
    volumes:
      - neo4j_data_dev:/data

  qdrant:
    volumes:
      - qdrant_data_dev:/qdrant/storage

  redis:
    volumes:
      - redis_data_dev:/data

  minio:
    volumes:
      - minio_data_dev:/data


  # ==============================================
  # ADDITIONAL CONTAINERS FOR DEVELOPMENT ONLY
  # ==============================================

  redis_insight:
    image: redis/redisinsight:latest
# To test in local dev, enable tunnel profile
    restart: unless-stopped
    environment:
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379
      RI_REDIS_USERNAME: ${SOURCE_CONTEXT_REDIS_USER:?SOURCE_CONTEXT_REDIS_USER is required}
      RI_REDIS_PASSWORD: ${SOURCE_CONTEXT_REDIS_PASSWORD:?SOURCE_CONTEXT_REDIS_PASSWORD is required}
      RI_REDIS_DB: 0
    volumes:
      - redis_insight_data_dev:/data
    ports:
      - "127.0.0.1:${SOURCE_CONTEXT_REDIS_INSIGHT_PORT:-5540}:5540"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:5540/api/health/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${SOURCE_CONTEXT_MAILHOG_SMTP_PORT:-1025}:1025"
      - "127.0.0.1:${SOURCE_CONTEXT_MAILHOG_HTTP_PORT:-8025}:8025"

  # ==============================================
  # OBSERVABILITY IS DISABLE BY DEFAULT
  # ==============================================
  alloy:
    profiles: [ logging ]
  loki:
    profiles: [ logging ]
    volumes:
      - loki_data_dev:/loki
  grafana:
    profiles: [ logging ]

volumes:
  postgres_data_dev:
  neo4j_data_dev:
  qdrant_data_dev:
  redis_data_dev:
  minio_data_dev:
  redis_insight_data_dev:

  loki_data_dev: