services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:${BACKEND_EXTERNAL_PORT:-8000}:8000"


  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:${FRONTEND_EXTERNAL_PORT:-5173}:5173"


  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d/
    ports:
      - "127.0.0.1:${DB_EXTERNAL_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


  neo4j:
    image: neo4j:community
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD?-Variable is empty or not set}
    ports:
      # For web UI
      - "127.0.0.1:${NEO4J_EXTERNAL_HTTP_PORT:-7474}:7474"
      # For driver
      - "127.0.0.1:${NEO4J_EXTERNAL_BOLT_PORT:-7687}:7687"
    healthcheck:
      test: [
        "CMD",
        "cypher-shell",
        "-u", "${NEO4J_USERNAME?-Variable is empty or not set}",
        "-p", "${NEO4J_PASSWORD?-Variable is emtpy or not set}",
        "RETURN 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${QDRANT_EXTERNAL_PORT_HTTP:-6333}:6333"
      - "127.0.0.1:${QDRANT_EXTERNAL_PORT_GRPC:-6334}:6334"
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY?-Variable is empty or not set}
      - QDRANT__TELEMETRY_DISABLED=true
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s


  redis:
    image: redis:8.6
    restart: unless-stopped
    ports:
      - "127.0.0.1:${REDIS_EXTERNAL_PORT:-6379}:6379"
    command: >
      redis-server
      --user default off
      --user ${REDIS_USER:?Variable is not set or empty} on ">${REDIS_PASSWORD:?Variable is not set or empty}" allcommands allkeys allchannels
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s


  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER?-Variable is empty or not set}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD?-Variable is empty or not set}
    command: server /data --address :9000 --console-address :9001
    ports:
      - "127.0.0.1:${MINIO_API_EXTERNAL_PORT:-9000}:9000"
      - "127.0.0.1:${MINIO_CONSOLE_EXTERNAL_PORT:-9001}:9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s


  