[project]
name = "source-context-mcp"
version = "0.1.dev1"
description = "Local MCP server for your agents."
readme = "README.md"
authors = [
    { name = "Le Ngoc Tu", email = "tuleaibk@gmail.com" },
    { name = "Dang Huu Hieu", email = "danghuuhieu038@gmail.com"},
    { name = "Huynh Phat Tai", email = "huynhphtai@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp",
]

[project.scripts]
source-context-mcp = "source_context_mcp.__main__:main"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[tool.ruff]
extend = "../pyproject.toml"