name: Deploy backend

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - "uv.lock"
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/backend

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      #https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v6

      # https://github.com/docker/login-action
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./backend/Dockerfile
          context: .
          target: prod
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME | lower }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME | lower }}:${{ github.ref_name }}